export const SchemaTypes = {
  UUID: 'UUID',
  BOOLEAN: 'BOOLEAN',
  STRING: 'VARCHAR',
  CASCADE: 'CASCADE',
  INT: 'INT',
  FLOAT: 'FLOAT',
  TIMESTAMP: 'TIMESTAMP',
  UNIQUE: 'UNIQUE',
  TEXT: 'TEXT'
};
